# Generated by Django 5.0.3 on 2024-03-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departement',
            new_name='Departements',
        ),
    ]
